version: '3'
services:
  web:
    image: 425750527999.dkr.ecr.us-east-1.amazonaws.com/ec2-tutorial:latest
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs-tutorial
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs-tutorial
